spring.application.name=code

# Database configuration for MySQL
# Update the URL, username, and password as per your MySQL setup
# Create the 'inventory' database in MySQL before running the application!

spring.datasource.url=jdbc:mysql://localhost:3306/inventory?useSSL=false
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# MongoDB configuration for reviews
spring.data.mongodb.uri=mongodb://localhost:27017/reviews?authSource=admin

management.endpoint.health.show-details=always
management.health.db.enabled=true
